stages:
  - 005_dev

deploy to dev:
  stage: 005_dev
  when: always
  retry: 2
  only:
    refs:
      - main
  script:
    - ls -lah
    # - docker compose stop || true
    # - docker compose rm || true
    # - docker system prune || true
    - cd ./docker
    - docker compose build
    - docker compose up -d
    - sleep 5
  tags:
    - 005-dev
