stages:
  - 005_dev

deploy to dev:
  stage: 005_dev
  when: always
  retry: 2
  only:
    refs:
      - main
  script:
    - rsync -av --no-perms --no-owner --no-group --exclude ".git*" $CI_PROJECT_DIR/ /data/project/
    - ls -lah /data/project
    - cd ./docker
    - docker compose stop || true
    - docker compose rm || true
    - docker system prune || true
    - chmod -R 777 /data/project/
    - docker compose build
    - docker compose up -d
    - sleep 5
  tags:
    - 005-dev
