# Generated by Django 3.1.3 on 2021-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_remove_product_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsizes',
            name='name_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='boxsizes',
            name='name_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='preview_text_en',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Preview Text'),
        ),
        migrations.AddField(
            model_name='category',
            name='preview_text_ru',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Preview Text'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_text_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Detail Text'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_text_ru',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Detail Text'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_text_en',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Preview Text'),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_text_ru',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Preview Text'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='preview_text_en',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Preview Text'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='preview_text_ru',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='Preview Text'),
        ),
    ]
