# Generated by Django 3.1.3 on 2021-06-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_auto_20210614_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimage', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('mainimage_en', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('mainimage_ru', models.ImageField(blank=True, null=True, upload_to='banner/')),
            ],
        ),
    ]
