# Generated by Django 3.1.3 on 2021-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calcbanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimage', models.ImageField(blank=True, null=True, upload_to='banner/')),
            ],
        ),
    ]
