# Generated by Django 3.1.3 on 2021-06-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_calcbanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calcbanner',
        ),
    ]
