# Generated by Django 3.1.3 on 2021-07-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_order_comment'),
        ('products', '0062_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
