# Generated by Django 3.1.3 on 2021-07-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=None, null=True),
        ),
    ]
