# Generated by Django 3.1.3 on 2021-07-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
