# Generated by Django 4.1.1 on 2022-09-25 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0067_auto_20210716_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='mainimage_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='mainimage_ru',
        ),
        migrations.RemoveField(
            model_name='boxsizes',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='boxsizes',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='preview_text_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='preview_text_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail_text_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail_text_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preview_text_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='preview_text_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='preview_text_en',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='preview_text_ru',
        ),
        migrations.AlterField(
            model_name='product',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='test',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
